### PR TITLE
Add note about changelog management

### PR DESCRIPTION
**Pull request by michaelsauter**

### CODE REVIEW

**Review by clemensutschig — APPROVED** [review]

**Review by clemensutschig — APPROVED** [review]

**Comment by michaelsauter** [comment]
@stitakis @tjaeschke @rattermeyer ping

**Comment by michaelsauter** [comment]
@stitakis @rattermeyer @tjaeschke ping

**Review by clemensutschig — DISMISSED** [review]

**Comment by clemensutschig** [comment]
@michaelsauter  - we should actively check for that in PR reviews

**Review by rattermeyer — DISMISSED** [review]

**Comment by michaelsauter** [comment]
@clemensutschig @rattermeyer @stitakis @tjaeschke I need two approvals to finally merge this. Can you please have a look? Thanks.

**Review by clemensutschig — APPROVED** [review]

**Review by rattermeyer — APPROVED** [review]
looks good to me now.

**Pull request merged**
